# src: .github/workflows/
name: Build and deploy a container to an Azure Container Apps - ACA

env:
  IMAGE_NAME: acrdemoaca.azurecr.io/backend-githubactions
  CONTAINERAPPS_APP: githubactions-backend
  CONTAINERAPPS_ENVIRONMENT: managedEnvironment-rgaca-824e
  RESOURCE_GROUP: rg-aca

on: workflow_dispatch:

jobs:
  build-push-container-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to azure container registry
        uses: Azure/docker-login@v1
        with:
          login-server: acrdemoaca.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push   
        run: |
            docker build . -t ${{env.IMAGE_NAME}}:${{ github.run_number }}
            docker push ${{env.IMAGE_NAME}}:${{ github.run_number }}

  deploy-to-container-apps:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-push-container-image

    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        registryUrl: acrdemoaca.azurecr.io
        imageToDeploy: acrdemoaca.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}
        targetPort: 3500
        ingress: external
        containerAppName: ${{ env.CONTAINERAPPS_APP }}
        containerAppEnvironment: ${{ env.CONTAINERAPPS_ENVIRONMENT }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
